### PR TITLE
Catch the invalid headers error

### LINKED ISSUE #46: Throws instead of rejecting the promise if a sent header value is invalid
Some sites, for example, [Armenia's government site](https://gov.am), have invalid header values. The example site sends a `X-Frame-Options` header set to `â€œDENYâ€`, which, obviously, contains invalid characters.

The function `checkInvalidHeaderChar` will throw an error if a header value contains an invalid character. When throwing in promises, the error is usually caught. But this code
```js
const fetch = require('electron-fetch')

(async() => {
	try {
		await fetch('https://gov.am/en/');
	} catch (e) {
		console.log(`caught: ${e}`)
	}
})
```
will throw an error, even though there is a `catch` block.

This is caused by `headers.append()`, which does the check ([L189](https://github.com/arantes555/electron-fetch/blob/master/src/index.js#L189)), located inside the callback of `req.on('response')` ([L147](https://github.com/arantes555/electron-fetch/blob/master/src/index.js#L147)).
When something throws inside a callback inside a Promise, there is no way to catch the error. What I'm saying is:
```js
function promiseThrowAfter1s() {
	return new Promise(() => {
		setTimeout(() => {
			throw new Error("gotcha");
		}, 1000)
	})
};

promiseThrowAfter1s().catch(() => {
	// never gets executed
})
```

A simple solution to that would be to wrap the `on('response')` listener with a try-catch block, and reject the promise when caught.

*Another suggestion*

Maybe provide an option like `sanitizeHeaders: boolean` so that the user can ignore invalid headers, because invalid headers don't create any unexpected errors in electron imo.

### PR DESCRIPTION
**Pull request by wheezard**
This PR will create a new kind of `FetchError`: "Invalid response".
It will be thrown when an error happens while receiving the response, for example, when the response headers are invalid.

*Tests:*
1. (un)Fortunately, Node.js doesn't allow to set invalid headers as a server, so I had to use https://gov.am/en/ for that (I've never seen an invalid header before lol)
2. The invalid headers are handled differently by Node and Electron. Node.js seems to automatically remove invalid characters and continue on, but Electron does nothing.

Because of point 2, maybe it will be more reasonable to remove invalid characters in an Electron environment as well? For example, in `sanitizeValue`, we could try to just ignore all the invalid characters like Node.js does.

This PR does not introduce any changes to the API yet. I'm hoping to discuss how `electron-fetch` should handle this thing without breaking expectations or introducing weird errors.

Also closes #46.

### CODE REVIEW

**Comment by arantes555** [comment]
Hello ! Sorry for the delay in answering, I'm a bit overworked this week ^^

I'll try taking a look at this by the end of this week, probably over the week end. However, it seems that the linting is failing at the moment. Maybe you could fix it in the meantime? Otherwise, I could just fix it myself after review, no problem.

> 1. (un)Fortunately, Node.js doesn't allow to set invalid headers as a server, so I had to use https://gov.am/en/ for that (I've never seen an invalid header before lol)

Works for me 🤷 

>     2. The invalid headers are handled differently by Node and Electron. Node.js seems to automatically remove invalid characters and continue on, but Electron does nothing.
> 
> 
> Because of point 2, maybe it will be more reasonable to remove invalid characters in an Electron environment as well? For example, in `sanitizeValue`, we could try to just ignore all the invalid characters like Node.js does.

Do you know how different browsers handle this ? If Firefox, Chrome, and Safari all handle it in the same way, we should just handle it like they do (if possible). I believe sticking to how actual `window.fetch` behaves is more important than sticking to how the node implementation can behave.

**Comment by wheezard** [comment]
> Hello ! Sorry for the delay in answering, I'm a bit overworked this week ^^

No worries!

> However, it seems that the linting is failing at the moment.

Oops, didn't run lint before committing, fixed it in the next commit.

> Do you know how different browsers handle this ?

All browsers handle it the same way. They ignore invalid characters unless they're important: if you embed the Armenian website in an `<iframe>`, chromium browsers will display this error:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://www.gov.am/': '“DENY”' is not a recognized directive. The header will be ignored.
```
However, following this implementation is not ideal because Node.js will remove the invalid characters automatically and Electron won't. This means that on Node.js, this aspect of Fetch API isn't possible to follow. Also, following this implementation will introduce a difference in how electron-fetch works on Electron and on Node.

I also think that this is not a big enough deal, because invalid headers are pretty rare so we don't have to worry too much about this. I guess we can implement something like `validate: boolean` in the `Headers` constructor.

**Comment by wheezard** [comment]
> Works for me 🤷

Oh, also about that first point in the PR description: I meant in the tests we use a Node.js server so it's impossible to set invalid headers.

**Comment by arantes555** [comment]
Sorry for the delay in reviewing this ... been quite busy this past month.

I am trying to run the tests now, but the call to https://gov.am/en/ does not seem to throw the expected error anymore. Maybe they fixed their server ?

File: test/test.js [hunk 1]
```diff
@@ -210,6 +210,21 @@ const createTestSuite = (useElectronNet) => {
       })
     })
 
+    if (useElectronNet) {
+      // for some reason, Node.js parses the header value differently
+      // so this test doesn't work in node, only in electron
+      it('should reject with error when headers contain invalid symbols', function () {
+        url = 'https://gov.am/en/'
```
Comment (arantes555) [inline test/test.js:217]:
```suggestion
        this.timeout(5000)
        url = 'https://www.gov.am/en/'
```

**Comment by arantes555** [comment]
Actually, your test does seem to pass as intended in local, it just timeouts in CI... I took the liberty of pushing a bigger timeout to the test into your branch

File: test/test.js [hunk 2]
```diff
@@ -210,6 +210,22 @@ const createTestSuite = (useElectronNet) => {
       })
     })
 
+    if (useElectronNet) {
+      // for some reason, Node.js parses the header value differently
+      // so this test doesn't work in node, only in electron
+      it('should reject with error when headers contain invalid symbols', function () {
+        this.timeout(5000)
```
Comment (arantes555) [inline test/test.js:217]:
```suggestion
        this.timeout(10000)
```

**Comment by wheezard** [comment]
Honestly, the whole CI stuff is pretty new for me, so I can't really help with that, sorry 😅

File: test/test.js [hunk 3]
```diff
@@ -210,6 +210,22 @@ const createTestSuite = (useElectronNet) => {
       })
     })
 
+    if (useElectronNet) {
+      // for some reason, Node.js parses the header value differently
+      // so this test doesn't work in node, only in electron
+      it('should reject with error when headers contain invalid symbols', function () {
+        this.timeout(10000)
```
Comment (arantes555) [inline test/test.js:217]:
```suggestion
    if (useElectronNet && !process.env.CI) {
      // for some reason, Node.js parses the header value differently
      // so this test doesn't work in node, only in electron
      // Also, this test somehow fails 80% of the time in CI...
      // probably because the test matrix overloads the remote server or something?
      it('should reject with error when headers contain invalid symbols', function () {
```

File: test/test.js [hunk 4]
```diff
@@ -210,6 +210,24 @@ const createTestSuite = (useElectronNet) => {
       })
     })
 
+    if (useElectronNet) {
+      // for some reason, Node.js parses the header value differently
+      // so this test doesn't work in node, only in electron
+      it('should reject with error when headers contain invalid symbols', function () {
+      // This test somehow fails 80% of the time in CI...
+      // probably because the test matrix overloads the remote server or something?
+      if (process.env.CI) return this.skip()
```
Comment (arantes555) [inline test/test.js:219]:
```suggestion
        // This test somehow fails 80% of the time in CI...
        // probably because the test matrix overloads the remote server or something?
        if (process.env.CI) return this.skip()
```
